/* Menologe : saints du jour, par date « nominale » (la date du calendrier de l’Église).
   Préfixes : ** = grand saint / grande fête ; * = saint notable ; sans préfixe = commémoration. */
(function () {
  const O = (window.ORTHO = window.ORTHO || {});
  O.SAINTS = {
    '01-01': ['**Circoncision du Seigneur', '**Saint Basile le Grand, archevêque de Césarée'],
    '01-02': ['*Saint Séraphin de Sarov (repos, 1833)', 'Saint Sylvestre, pape de Rome'],
    '01-03': ['*Sainte Geneviève, patronne de Paris (vers 512)', 'Prophète Malachie'],
    '01-04': ['Synaxe des soixante-dix Apôtres', 'Saint Théoctiste'],
    '01-05': ['Veille de la Théophanie', 'Saints martyrs Théopempte et Théonas', 'Sainte Syncletique'],
    '01-06': ['**Sainte Théophanie — Baptême du Seigneur'],
    '01-07': ['**Synaxe de saint Jean le Précurseur et Baptiste'],
    '01-08': ['Saint Georges le Chozébite', 'Sainte Domnika'],
    '01-09': ['Saint Polyeucte, martyr', 'Saint Eustrate'],
    '01-10': ['*Saint Grégoire de Nysse', 'Saint Domitien de Mélitène'],
    '01-11': ['*Saint Théodose le Cénobiarque'],
    '01-12': ['Sainte Tatiana, martyre', 'Saint Mercure de Césarée'],
    '01-13': ['Saints Hermyle et Stratonique', 'Saint Hilaire de Poitiers'],
    '01-14': ['*Saint Hilaire de Poitiers, confesseur (367)', 'Saints Pères massacrés au Sinaï et à Raïthou'],
    '01-15': ['*Saints Paul de Thèbes et Jean la Cabane'],
    '01-16': ['Vénération des chaînes de saint Pierre', 'Saint Honorat d’Arles'],
    '01-17': ['**Saint Antoine le Grand, père du monachisme (356)'],
    '01-18': ['**Saints Athanase et Cyrille, patriarches d’Alexandrie'],
    '01-19': ['*Saint Macaire d’Égypte', 'Saint Marc d’Éphèse'],
    '01-20': ['**Saint Euthyme le Grand'],
    '01-21': ['*Saint Maxime le Confesseur', 'Sainte Agnès de Rome'],
    '01-22': ['Apôtre Timothée', 'Saint Anastase le Perse'],
    '01-23': ['Saint Clément d’Ancyre', 'Saint Agathange'],
    '01-24': ['*Sainte Xénie de Rome', 'Saint Théodule'],
    '01-25': ['**Saint Grégoire le Théologien, archevêque de Constantinople'],
    '01-26': ['Saint Xénophon et sa famille'],
    '01-27': ['*Translation des reliques de saint Jean Chrysostome'],
    '01-28': ['*Saint Éphrem le Syrien', 'Saint Paul de Thèbes'],
    '01-29': ['Translation des reliques de saint Ignace le Théophore'],
    '01-30': ['**Les trois Hiérarques : saints Basile le Grand, Grégoire le Théologien et Jean Chrysostome'],
    '01-31': ['*Saints Cyr et Jean, anargyres'],

    '02-01': ['Saint Tryphon, martyr', 'Sainte Brigitte de Kildare'],
    '02-02': ['**Présentation du Seigneur au Temple'],
    '02-03': ['*Syméon le Dieu-Porteur et la prophétesse Anne'],
    '02-04': ['*Saint Isidore de Péluse'],
    '02-05': ['Sainte Agathe, martyre'],
    '02-06': ['Saint Bucolos de Smyrne', 'Sainte Photine'],
    '02-07': ['Saint Parthène de Lampsaque'],
    '02-08': ['*Saint Théodore Stratilate, grand martyr', 'Saint Zacharie'],
    '02-09': ['Saint Nicéphore d’Antioche'],
    '02-10': ['*Saint Haralampe, hiéromartyr'],
    '02-11': ['*Saint Blaise de Sébaste', 'Saint Damase'],
    '02-12': ['*Saint Mélèce d’Antioche'],
    '02-13': ['Apôtres Aquilas et Priscille'],
    '02-14': ['Saint Auxence', 'Saint Cyrille le Philosophe (moine à Rome)'],
    '02-15': ['Apôtre Onésime'],
    '02-16': ['Saint Pamphile, martyr'],
    '02-17': ['*Saint Théodore le Tiron (le Conscrit)'],
    '02-18': ['*Saint Léon le Grand, pape de Rome', 'Saint Agapit'],
    '02-19': ['Apôtre Archippe'],
    '02-20': ['Saint Léon de Catane'],
    '02-21': ['Saint Timothée de Symbola'],
    '02-22': ['Découverte des reliques à Eugénie'],
    '02-23': ['*Saint Polycarpe de Smyrne'],
    '02-24': ['Première et seconde découverte du chef de saint Jean-Baptiste'],
    '02-25': ['*Saint Tarasios de Constantinople'],
    '02-26': ['Saint Porphyre de Gaza', 'Saint Alexandre d’Alexandrie'],
    '02-27': ['*Saint Procope le Décapolite'],
    '02-28': ['Saint Basile le Confesseur'],
    '02-29': ['*Saint Jean Cassien le Romain'],

    '03-01': ['Sainte Eudocie, martyre'],
    '03-02': ['Saint Théodote de Cyrénie', 'Saint Hésychius'],
    '03-03': ['Saints Eutrope, Cléonique et Basilisque'],
    '03-04': ['*Saint Gérasime du Jourdain'],
    '03-05': ['Saint Conon, martyr'],
    '03-06': ['Les quarante-deux martyrs d’Amorium'],
    '03-07': ['Saints évêques de Chersonèse'],
    '03-08': ['Saint Théophylacte, évêque de Nicomédie'],
    '03-09': ['**Les Quarante Martyrs de Sébaste'],
    '03-10': ['Saint Codrat et ses compagnons'],
    '03-11': ['*Saint Sophrone de Jérusalem'],
    '03-12': ['*Saint Théophane le Confesseur', '*Saint Grégoire le Grand, pape de Rome'],
    '03-13': ['Translation des reliques de saint Nicéphore de Constantinople'],
    '03-14': ['*Saint Benoît de Nursie'],
    '03-15': ['Saint Agapios'],
    '03-16': ['Martyr Sabin d’Égypte'],
    '03-17': ['*Saint Alexis, homme de Dieu', '*Saint Patrick, illuminateur de l’Irlande'],
    '03-18': ['*Saint Cyrille de Jérusalem'],
    '03-19': ['Saints Chrysanthe et Darie'],
    '03-20': ['Saints Pères massacrés au monastère de Saint-Sabbas'],
    '03-21': ['*Saint Jacques le Confesseur'],
    '03-22': ['Saint Basile d’Ancyre'],
    '03-23': ['Saint Nicon et ses disciples'],
    '03-24': ['Veille de l’Annonciation'],
    '03-25': ['**Annonciation de la Mère de Dieu'],
    '03-26': ['*Synaxe de l’archange Gabriel'],
    '03-27': ['Saint Matrone de Thessalonique', 'Saint Jean l’Égyptien'],
    '03-28': ['Saint Hilarion le Nouveau'],
    '03-29': ['Saint Marc d’Aréthuse'],
    '03-30': ['**Saint Jean Climaque, auteur de l’Échelle sainte'],
    '03-31': ['Saint Hypatios de Gangres', 'Sainte Balbine'],

    '04-01': ['*Sainte Marie l’Égyptienne'],
    '04-02': ['*Saint Tite le Thaumaturge', 'Saint Jean de Rhodes'],
    '04-03': ['Saint Nicétas le Confesseur'],
    '04-04': ['*Saint Joseph l’Hymnographe', 'Saint Isidore de Séville'],
    '04-05': ['Saints Théodule et Agathopode'],
    '04-06': ['Saint Eutychius de Constantinople'],
    '04-07': ['Saint Georges de Mytilène'],
    '04-08': ['Apôtres Hérodion, Agabus et Rufus'],
    '04-09': ['Saint Eupsychius'],
    '04-10': ['Saint Terence et ses compagnons'],
    '04-11': ['*Saint Antipas de Pergame'],
    '04-12': ['*Saint Basile le Confesseur de Parium'],
    '04-13': ['*Saint Martin le Confesseur, pape de Rome'],
    '04-14': ['Apôtre Aristarque, Pudens et Trophime'],
    '04-15': ['Sainte Basilisse', 'Saint Aristarque'],
    '04-16': ['Saintes Agapé, Irène et Chionie'],
    '04-17': ['Saint Siméon le Perse'],
    '04-18': ['Saint Jean de la Laure de Saint-Sabbas'],
    '04-19': ['Saint Jean le Vieux', 'Saint Paphnuce'],
    '04-20': ['Saint Théodore le Trichinas'],
    '04-21': ['Hiéromartyr Janvier'],
    '04-22': ['Saint Théodore de Sykéon'],
    '04-23': ['**Saint Georges le Victorieux, grand martyr'],
    '04-24': ['Sainte Élisabeth la Thaumaturge', 'Saint Sabbas Stratilate'],
    '04-25': ['**Apôtre et évangéliste Marc'],
    '04-26': ['Saint Basile d’Amasée'],
    '04-27': ['Saint Syméon, parent du Seigneur'],
    '04-28': ['Apôtres Jason et Sosipater'],
    '04-29': ['Les neuf martyrs de Cyzique'],
    '04-30': ['*Apôtre Jacques, fils de Zébédée'],

    '05-01': ['Prophète Jérémie'],
    '05-02': ['*Saint Athanase le Grand', '*Saints Boris et Gleb, passion-porteurs'],
    '05-03': ['Saints Timothée et Maure'],
    '05-04': ['*Sainte Pélagie de Tarse'],
    '05-05': ['Sainte Irène de Thessalonique'],
    '05-06': ['*Saint Job le Juste'],
    '05-07': ['Apparition de la Croix à Jérusalem'],
    '05-08': ['**Apôtre et évangéliste Jean le Théologien'],
    '05-09': ['*Prophète Isaïe', 'Saint Christophe'],
    '05-10': ['Apôtre Simon le Zélote'],
    '05-11': ['**Saints Cyrille et Méthode, égaux aux Apôtres, illuminateurs des Slaves'],
    '05-12': ['*Saint Épiphane de Chypre', 'Saint Germain de Constantinople'],
    '05-13': ['Sainte Glycérie'],
    '05-14': ['Saint Isidore de Chios'],
    '05-15': ['*Saint Pachôme le Grand'],
    '05-16': ['*Saint Théodore le Sanctifié', 'Saint Brendan'],
    '05-17': ['Apôtres Andronic et Junie'],
    '05-18': ['Saint Théodote d’Ancyre'],
    '05-19': ['Saint Patrice de Pruse'],
    '05-20': ['Saint Thalélée'],
    '05-21': ['**Saints Constantin et Hélène, égaux aux Apôtres'],
    '05-22': ['Saint Basilisque de Comane'],
    '05-23': ['Saint Michel de Synnades'],
    '05-24': ['Saint Syméon du Mont Admirable', 'Saint Vincent de Lérins'],
    '05-25': ['Troisième découverte du chef de saint Jean-Baptiste'],
    '05-26': ['Apôtre Carpe'],
    '05-27': ['*Saint Jean le Russe'],
    '05-28': ['Saint Nicétas, évêque de Rémésiane'],
    '05-29': ['Sainte Théodosie, martyre'],
    '05-30': ['Saint Isaac de Dalmatie'],
    '05-31': ['Saint Hermias, martyr'],

    '06-01': ['**Saint Justin le Philosophe, martyr'],
    '06-02': ['Saint Nicéphore le Confesseur'],
    '06-03': ['Saint Lucillien et ses compagnons'],
    '06-04': ['Saint Métrophane de Constantinople'],
    '06-05': ['*Saint Dorothée de Tyr', 'Saint Boniface'],
    '06-06': ['*Saint Hilarion le Nouveau'],
    '06-07': ['Saint Théodote'],
    '06-08': ['Saint Théodore Stratilate'],
    '06-09': ['*Saint Cyrille d’Alexandrie', 'Saint Colomba d’Iona'],
    '06-10': ['Saints Alexandre et Antonine'],
    '06-11': ['*Apôtres Barthélemy et Barnabé'],
    '06-12': ['*Saint Onuphre le Grand', 'Saint Pierre de l’Athos'],
    '06-13': ['Sainte Aquilina'],
    '06-14': ['*Prophète Élisée', 'Saint Méthode de Constantinople'],
    '06-15': ['Prophète Amos', 'Bienheureux Augustin d’Hippone', 'Bienheureux Jérôme de Stridon'],
    '06-16': ['Saint Tychon d’Amathonte'],
    '06-17': ['Saints Manuel, Sabel et Ismaël'],
    '06-18': ['Saints Léonce, Hypatius et Théodule'],
    '06-19': ['*Apôtre Jude, frère du Seigneur'],
    '06-20': ['Saint Méthode de Patara'],
    '06-21': ['Saint Julien de Tarse'],
    '06-22': ['Saint Eusèbe de Samosate', 'Saint Alban de Verulamium'],
    '06-23': ['Sainte Agrippine'],
    '06-24': ['**Nativité de saint Jean le Précurseur'],
    '06-25': ['Sainte Fébronie de Nisibe'],
    '06-26': ['*Saint David de Thessalonique'],
    '06-27': ['Saint Samson l’Hospitalier'],
    '06-28': ['Translation des reliques de saints Cyr et Jean'],
    '06-29': ['**Saints Apôtres Pierre et Paul'],
    '06-30': ['**Synaxe des douze Apôtres'],

    '07-01': ['*Saints Cosme et Damien de Rome'],
    '07-02': ['Dépôt de la robe de la Mère de Dieu aux Blachernes'],
    '07-03': ['Saint Hyacinthe'],
    '07-04': ['*Saint André de Crète'],
    '07-05': ['*Saint Athanase de l’Athos'],
    '07-06': ['Saint Sisoès le Grand'],
    '07-07': ['Sainte Cyriaque'],
    '07-08': ['*Saint Procope, grand martyr'],
    '07-09': ['Saint Pancrace de Taormine'],
    '07-10': ['Les quarante-cinq martyrs de Nicopolis'],
    '07-11': ['*Sainte Euphémie de Chalcédoine', '*Sainte Olga, égale aux Apôtres'],
    '07-12': ['Saints Procle et Hilarion', '*Saint Païssios de l’Athos'],
    '07-13': ['Synaxe de l’archange Gabriel'],
    '07-14': ['Apôtre Aquilas'],
    '07-15': ['*Saint Vladimir, égal aux Apôtres'],
    '07-16': ['Saint Athénogène'],
    '07-17': ['*Sainte Marine, grande martyre'],
    '07-18': ['Saint Émilien'],
    '07-19': ['*Sainte Macrine, sœur de saint Basile', 'Saint Dius'],
    '07-20': ['**Prophète Élie'],
    '07-21': ['Saint Syméon le Fol-en-Christ'],
    '07-22': ['**Sainte Marie-Madeleine, égale aux Apôtres'],
    '07-23': ['Saint Apollinaire de Ravenne', 'Saint Phocas'],
    '07-24': ['*Saints Boris et Gleb, passion-porteurs', 'Sainte Christine'],
    '07-25': ['*Dormition de sainte Anne, mère de la Mère de Dieu'],
    '07-26': ['*Saint Hermolaos', 'Sainte Parascève'],
    '07-27': ['*Saint Pantéléimon, grand martyr et guérisseur'],
    '07-28': ['Apôtres Prochore et Nicanor'],
    '07-29': ['Sainte Marthe, sœur de Lazare', 'Saint Callinique'],
    '07-30': ['Apôtre Silas et ses compagnons'],
    '07-31': ['*Saint Germain d’Auxerre', 'Saint Eudocime le Juste'],

    '08-01': ['*Découverte des reliques de saint Séraphin de Sarov', 'Saints Maccabées', 'Début du Carême de la Dormition'],
    '08-02': ['Translation des reliques de saint Étienne'],
    '08-03': ['Saints Isaac, Dalmate et Faustus'],
    '08-04': ['*Les sept dormants d’Éphèse'],
    '08-05': ['Veille de la Transfiguration', 'Saint Eusignios'],
    '08-06': ['**Transfiguration de notre Seigneur'],
    '08-07': ['Saint Dométios'],
    '08-08': ['Saint Émilien de Cyzique'],
    '08-09': ['**Apôtre Matthias'],
    '08-10': ['*Saint Laurent, archidiacre de Rome'],
    '08-11': ['Saint Euplus'],
    '08-12': ['Saints Photius et Aniketos'],
    '08-13': ['*Saint Maxime le Confesseur'],
    '08-14': ['Veille de la Dormition', 'Prophète Michée'],
    '08-15': ['**Dormition de la Mère de Dieu'],
    '08-16': ['Translation du saint Mandylion', 'Saint Diomède'],
    '08-17': ['Saint Myron'],
    '08-18': ['Saints Flore et Laure'],
    '08-19': ['Saint André Stratilate'],
    '08-20': ['Prophète Samuel'],
    '08-21': ['Apôtre Thaddée'],
    '08-22': ['Saint Agathonique'],
    '08-23': ['*Saint Irénée, évêque de Lyon', 'Saint Lupus'],
    '08-24': ['*Saint Cosmas d’Étolie', 'Saint Eutychès'],
    '08-25': ['*Apôtre Barthélemy', 'Translation des reliques de l’apôtre Tite'],
    '08-26': ['Saints Adrien et Nathalie'],
    '08-27': ['*Saint Pimène le Grand'],
    '08-28': ['*Saint Moïse l’Éthiopien'],
    '08-29': ['**Décollation de saint Jean le Précurseur'],
    '08-30': ['Saints Alexandre, Jean et Paul le Nouveau, patriarches de Constantinople'],
    '08-31': ['Dépôt de la ceinture de la Mère de Dieu'],

    '09-01': ['**Début de l’année ecclésiastique', '*Saint Syméon le Stylite', 'Saint Josué fils de Navé'],
    '09-02': ['Saint Mamas'],
    '09-03': ['Saint Anthyme de Nicomédie'],
    '09-04': ['Prophète Moïse', 'Saint Babylas'],
    '09-05': ['Prophète Zacharie, père du Précurseur'],
    '09-06': ['Miracle de l’archange Michel à Colosses'],
    '09-07': ['Veille de la Nativité de la Mère de Dieu', 'Saint Sozon'],
    '09-08': ['**Nativité de la Mère de Dieu'],
    '09-09': ['*Saints Joachim et Anne'],
    '09-10': ['Saintes Ménodora, Métrodora et Nymphodora'],
    '09-11': ['*Sainte Théodora d’Alexandrie', 'Saint Paphnuce'],
    '09-12': ['Saint Autonome'],
    '09-13': ['Dédicace de l’église de la Résurrection'],
    '09-14': ['**Exaltation de la Sainte Croix'],
    '09-15': ['**Saint Nicétas le Grand martyr'],
    '09-16': ['*Sainte Euphémie, grande martyre'],
    '09-17': ['**Saintes Foi, Espérance, Charité et leur mère Sophie'],
    '09-18': ['Saint Eumène de Gortyne'],
    '09-19': ['Saints Trophime, Sabbatios et Dorymédon'],
    '09-20': ['*Saint Eustathe Placidas, grand martyr'],
    '09-21': ['Apôtre Quadrat'],
    '09-22': ['Saint Phocas', 'Prophète Jonas'],
    '09-23': ['**Conception de saint Jean le Précurseur'],
    '09-24': ['*Sainte Thècle, égale aux Apôtres', '*Saint Silouane de l’Athos'],
    '09-25': ['*Saint Serge de Radonège', 'Sainte Euphrosyne'],
    '09-26': ['**Passage de saint Jean le Théologien'],
    '09-27': ['Saint Callistrate'],
    '09-28': ['Saint Chariton le Confesseur'],
    '09-29': ['*Saint Cyriaque l’Anachorète'],
    '09-30': ['Saint Grégoire l’Illuminateur de l’Arménie'],

    '10-01': ['**Protection de la Mère de Dieu', '*Saint Romain le Mélode', 'Apôtre Ananie'],
    '10-02': ['Saint Cyprien et sainte Justine'],
    '10-03': ['*Saint Denys l’Aréopagite'],
    '10-04': ['Saint Hiérothée'],
    '10-05': ['Saint Charitine'],
    '10-06': ['**Apôtre Thomas'],
    '10-07': ['*Saints Serge et Bacchus, martyrs'],
    '10-08': ['Sainte Pélagie la Pénitente'],
    '10-09': ['**Apôtre Jacques, fils d’Alphée'],
    '10-10': ['Saint Eulampios'],
    '10-11': ['*Apôtre Philippe, l’un des sept diacres'],
    '10-12': ['Saints Probe et Taraque'],
    '10-13': ['Saints Carpus et Papylas'],
    '10-14': ['*Sainte Parascève'],
    '10-15': ['Saint Euthyme le Nouveau'],
    '10-16': ['Saint Longin le Centurion'],
    '10-17': ['*Prophète Osée', 'Saint Lazare, ami du Christ'],
    '10-18': ['**Apôtre et évangéliste Luc'],
    '10-19': ['Prophète Joël'],
    '10-20': ['*Saint Artémius, grand martyr'],
    '10-21': ['Saint Hilarion le Grand'],
    '10-22': ['Saint Abercius d’Hiérapolis'],
    '10-23': ['*Apôtre Jacques, frère du Seigneur'],
    '10-24': ['Saint Aréthas'],
    '10-25': ['Saints Marcien et Martyrius'],
    '10-26': ['**Saint Démétrios de Thessalonique, grand martyr'],
    '10-27': ['Saint Nestor'],
    '10-28': ['Saint Térence'],
    '10-29': ['Sainte Anastasie la Romaine'],
    '10-30': ['Saints Zénobe et Zénobie'],
    '10-31': ['Apôtres Stachys, Amplias, Urbain'],

    '11-01': ['**Saints Cosme et Damien d’Asie, anargyres'],
    '11-02': ['Saint Akindynos et ses compagnons'],
    '11-03': ['Saint Acepsimas'],
    '11-04': ['Saint Joannice le Grand'],
    '11-05': ['Saint Galation et Épistèmè'],
    '11-06': ['*Saint Paul le Confesseur'],
    '11-07': ['Les trente-trois martyrs de Mélitène'],
    '11-08': ['**Synaxe de l’archange Michel et des Puissances célestes'],
    '11-09': ['*Saint Nectaire d’Égine', 'Saint Onésiphore'],
    '11-10': ['Apôtre Olympas'],
    '11-11': ['*Saint Théodore le Studite', 'Saint Mennas'],
    '11-12': ['*Saint Jean l’Aumônier', '*Saint Martin de Tours'],
    '11-13': ['**Saint Jean Chrysostome'],
    '11-14': ['**Apôtre Philippe'],
    '11-15': ['Début du Carême de la Nativité', 'Saints Gourias, Samonas et Abibos'],
    '11-16': ['**Apôtre et évangéliste Matthieu'],
    '11-17': ['*Saint Grégoire le Thaumaturge'],
    '11-18': ['Saint Platon'],
    '11-19': ['Prophète Abdias', 'Saint Barlaam'],
    '11-20': ['Saint Grégoire le Décapolite'],
    '11-21': ['**Entrée de la Mère de Dieu au Temple'],
    '11-22': ['Apôtre Philémon'],
    '11-23': ['Saint Amphiloque d’Iconium', 'Saint Colomban'],
    '11-24': ['*Saint Clément de Rome'],
    '11-25': ['**Sainte Catherine d’Alexandrie, grande martyre'],
    '11-26': ['Saint Alype le Stylite'],
    '11-27': ['Saint Jacques le Perse'],
    '11-28': ['Saint Étienne le Nouveau'],
    '11-29': ['Saint Paramon'],
    '11-30': ['**Apôtre André le Premier-Appelé'],

    '12-01': ['Prophète Nahum'],
    '12-02': ['Prophète Habacuc'],
    '12-03': ['Prophète Sophonie'],
    '12-04': ['**Sainte Barbe, grande martyre', '*Saint Jean Damascène'],
    '12-05': ['*Saint Sabbas le Sanctifié'],
    '12-06': ['**Saint Nicolas, archevêque de Myre en Lycie'],
    '12-07': ['*Saint Ambroise de Milan'],
    '12-08': ['Saint Patapios'],
    '12-09': ['Conception de sainte Anne'],
    '12-10': ['Saints Ménas, Hermogène et Eugraphe'],
    '12-11': ['*Saint Daniel le Stylite'],
    '12-12': ['**Saint Spyridon de Trimythonte'],
    '12-13': ['*Sainte Lucie de Syracuse', 'Saints Eustrate, Auxence'],
    '12-14': ['Saints Thyrse, Callinique et Philémon'],
    '12-15': ['Saint Éleuthère'],
    '12-16': ['Prophète Aggée'],
    '12-17': ['Prophète Daniel et les trois jeunes gens'],
    '12-18': ['Saint Sébastien et ses compagnons', 'Saint Modeste'],
    '12-19': ['Saint Boniface'],
    '12-20': ['*Saint Ignace le Théophore', '*Saint Jean de Cronstadt'],
    '12-21': ['Sainte Julienne', 'Saint Thémistocle'],
    '12-22': ['*Sainte Anastasie, délivreuse des chaînes'],
    '12-23': ['Les dix martyrs de Crète'],
    '12-24': ['Veille de la Nativité', 'Sainte Eugénie'],
    '12-25': ['**Nativité de notre Seigneur Jésus-Christ'],
    '12-26': ['**Synaxe de la Mère de Dieu'],
    '12-27': ['**Saint Étienne, protomartyr et archidiacre'],
    '12-28': ['Les vingt mille martyrs de Nicomédie'],
    '12-29': ['Les saints Innocents tués par Hérode'],
    '12-30': ['Sainte Anysie'],
    '12-31': ['*Sainte Mélanie la Romaine']
  };

  /* Courtes notices biographiques (par date nominale du saint principal) */
  O.SAINT_LIVES = {
    '01-01': 'Basile (330-379), évêque de Césarée de Cappadoce, théologien de l’Esprit Saint et fondateur d’une vie monastique communautaire. Il organise la charité (la « Basiliade », premier grand hôpital) et rédige une liturgie encore célébrée dix fois par an.',
    '01-02': 'Prokhor Moshnine (1754-1833), moine de Sarov, accueille « tous ceux qui venaient » avec les mots « Ma joie, le Christ est ressuscité ! ». Il enseigne que le but de la vie chrétienne est l’acquisition du Saint-Esprit.',
    '01-03': 'Geneviève (vers 420-512) consacre sa vie à Dieu dès l’adolescence. En 451, elle exhorte les Parisiens à rester dans la ville menacée par les Huns, qui l’épargnent. Elle devient la patronne de Paris.',
    '01-17': 'Antoine (vers 251-356) se retire dans le désert d’Égypte après avoir entendu l’Évangile : « Va, vends ce que tu as ». Il est le « père des moines ». Athanase écrit sa vie, qui influencera toute la spiritualité chrétienne.',
    '01-18': 'Athanase (296-373), évêque d’Alexandrie, défenseur de la divinité du Christ contre l’arianisme, exilé cinq fois. Cyrille (376-444), patriarche d’Alexandrie, défenseur du titre « Mère de Dieu » au concile d’Éphèse.',
    '01-25': 'Grégoire de Nazianze (329-390), l’un des trois Cappadociens, surnommé « le Théologien » pour la profondeur de ses discours sur la Trinité. Poète et archevêque de Constantinople.',
    '01-30': 'Basile, Grégoire et Jean Chrysostome se disputaient la primauté. Dans une vision, ils se présentent ensemble : « Nous sommes un en Dieu ». Ils sont célébrés ensemble comme patrons de la culture chrétienne.',
    '02-23': 'Polycarpe (69-155), disciple de saint Jean, évêque de Smyrne, brûlé vif à 86 ans : « Voilà quatre-vingt-six ans que je le sers et il ne m’a fait aucun mal ; comment pourrais-je blasphémer mon Roi qui m’a sauvé ? »',
    '03-09': 'Quarante soldats chrétiens de la Légion XII se tiennent nus sur un lac gelé en Arménie (320) plutôt que de renier le Christ. Un geôlier, touché, se joint à eux pour compléter le nombre.',
    '03-14': 'Benoît de Nursie (480-547), père du monachisme occidental. Sa Règle (« Ora et labora ») est encore suivie aujourd’hui. Les Églises orthodoxes le vénèrent comme saint d’avant le schisme.',
    '03-17': 'Patrick (V<sup>e</sup> siècle), évangélisateur de l’Irlande, utilise le trèfle pour expliquer la Trinité. Évêque missionnaire, ancien esclave en Irlande.',
    '03-30': 'Jean (vers 579-649), higoumène du Sinaï, auteur de l’Échelle du Paradis qui décrit trente degrés de la vie spirituelle, lue chaque année pendant le Carême.',
    '04-01': 'Marie d’Égypte (V<sup>e</sup> siècle), ancienne courtisane d’Alexandrie, convertie à Jérusalem devant l’icône de la Mère de Dieu, passe quarante-sept ans de pénitence dans le désert au-delà du Jourdain. Son exemple est proposé à la veille de Pâques.',
    '04-23': 'Georges (mort en 303), officier romain originaire de Cappadoce, confesse le Christ sous Dioclétien et subit un long martyre. Il est le patron des soldats, et son icône (terrassant le dragon) est l’une des plus aimées.',
    '04-25': 'Marc, disciple de Pierre, évangéliste, fondateur de l’Église d’Alexandrie. Son Évangile est le plus court et le plus ancien.',
    '05-08': 'Jean, le « disciple bien-aimé », appelé « le Théologien » pour le prologue de son Évangile (« Au commencement était le Verbe »). Seul des Apôtres à ne pas mourir en martyr, il écrit aussi l’Apocalypse.',
    '05-11': 'Cyrille (827-869) et Méthode (815-885), de Thessalonique, inventent l’alphabet glagolitique pour traduire les Écritures et la liturgie en slavon. Ils sont à l’origine de la langue liturgique que vous apprenez ici.',
    '05-21': 'Constantin (272-337), premier empereur chrétien, convoque le concile de Nicée (325). Sa mère Hélène découvre la Croix du Christ à Jérusalem.',
    '06-01': 'Justin (vers 100-165), philosophe de Samarie converti au christianisme, fonde une école à Rome et défend la foi dans ses Apologies. Décapité sous Marc Aurèle.',
    '06-15': 'Augustin (354-430), évêque d’Hippone, auteur des Confessions, grand docteur de la grâce, est vénéré par l’Église orthodoxe comme « bienheureux ».',
    '07-11': 'Olga (vers 890-969), régente de Kiev, est la première dirigeante russe à se faire baptiser. Elle prépare la conversion de son petit-fils Vladimir.',
    '07-15': 'Vladimir (vers 958-1015), grand-prince de Kiev, baptisé en 988, convertit la Rus’. D’après la Chronique, ses envoyés à Constantinople dirent : « Nous ne savions plus si nous étions au ciel ou sur terre ».',
    '07-20': 'Élie le Thesbite, prophète de feu, défend la foi d’Israël contre Baal au mont Carmel, puis rencontre Dieu dans « le murmure d’une brise légère ». Il est enlevé au ciel sur un char de feu.',
    '07-22': 'Marie de Magdala, guérie par le Christ de sept démons, reste au pied de la Croix et la première témoigne de la Résurrection : l’Église l’appelle « apôtre des apôtres ».',
    '07-27': 'Pantéléimon, médecin de Nicomédie sous Dioclétien, soignait gratuitement au nom du Christ. Martyrisé en 305, il est l’un des saints « anargyres » (sans argent).',
    '08-01': 'Séraphin de Sarov (1754-1833), ermite et starets, reçoit des visiteurs de toute la Russie. Il laisse l’entretien avec Motovilov sur « le but de la vie chrétienne ».',
    '08-13': 'Maxime le Confesseur (580-662), théologien de génie, défend la pleine humanité du Christ (deux volontés) contre le monothélisme. Il subit la mutilation de la langue et de la main et meurt en exil.',
    '08-23': 'Irénée de Lyon (vers 130-202), disciple de Polycarpe, auteur de « Contre les hérésies ». C’est à lui que l’on doit : « La gloire de Dieu, c’est l’homme vivant ».',
    '09-17': 'Foi, Espérance et Charité, trois sœurs de 12, 10 et 9 ans, martyrisées à Rome avec leur mère Sophie (« Sagesse ») sous Hadrien.',
    '09-25': 'Serge de Radonège (vers 1314-1392), fondateur de la Laure de la Trinité-Saint-Serge près de Moscou. Il bénit le prince Dimitri Donskoï avant la bataille de Koulikovo et est le père spirituel de la Russie.',
    '10-26': 'Démétrios (mort vers 306), jeune officier de Thessalonique, martyr sous Maximien. Patron de la ville, dont il est le défenseur.',
    '11-09': 'Nectaire (1846-1920), métropolite de Pentapole, ermite et maître spirituel à Égine ; ses nombreux miracles de guérison en ont fait un saint populaire.',
    '11-12': 'Martin de Tours (316-397), soldat romain qui partage son manteau avec un pauvre à Amiens, devient évêque de Tours et fonde le monachisme en Gaule. Jean l’Aumônier (+619), patriarche d’Alexandrie, est le saint de la charité.',
    '11-13': 'Jean (347-407), surnommé « Chrysostome » (« Bouche d’or »), archevêque de Constantinople, prédicateur éblouissant, exilé deux fois pour avoir dénoncé le luxe de la cour. Son homélie pascale est lue chaque année.',
    '11-25': 'Catherine (IV<sup>e</sup> siècle), jeune érudite d’Alexandrie, confond cinquante philosophes de l’empereur avant d’être martyrisée. Patronne des étudiants et philosophes.',
    '11-30': 'André, frère de Pierre, est le premier disciple appelé par Jésus. Il évangélise les terres du Pont-Euxin et est crucifié à Patras sur une croix en X.',
    '12-04': 'Barbe (III<sup>e</sup> siècle), enfermée dans une tour par son père païen, refuse de renier le Christ. Patronne des mineurs et des artilleurs. Jean Damascène (676-749), défenseur des icônes.',
    '12-06': 'Nicolas (IV<sup>e</sup> siècle), évêque de Myre, connu pour sa générosité envers les pauvres, notamment trois jeunes filles sans dot. Il participe au concile de Nicée. Il est le saint le plus populaire du monde orthodoxe.',
    '12-12': 'Spyridon (mort vers 348), berger devenu évêque de Chypre, participe au concile de Nicée : il illustre l’unité des trois personnes divines avec une brique qui devient feu, eau et terre.',
    '12-27': 'Étienne, l’un des sept premiers diacres, est le premier martyr chrétien (vers 36), lapidé à Jérusalem en priant : « Seigneur, ne leur impute pas ce péché ».'
  };
})();
